# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT
sudo apt-get update
sudo apt-get install -y git vim emacs automake bison flex gperf build-essential libfuse2 python-dev python-pip
sudo apt-get install autoconf2.64 # sometimes this older version is needed
sudo pip install --upgrade twisted

# make a fuse install for java
cd /tmp
sudo apt-get download fuse
sudo dpkg-deb -x fuse_* .
sudo dpkg-deb -e fuse_*
sudo rm fuse_*.deb
sudo echo -en '#!/bin/bash\nexit 0\n' > DEBIAN/postinst
sudo dpkg-deb -b . /fuse.deb
sudo dpkg -i /fuse.deb

# install java
sudo apt-get install -y openjdk-6-jre openjdk-6-jdk

# install nesC

cd /home/vagrant
git clone git://github.com/tinyos/nesc.git 
cd nesc
sudo ./Bootstrap
sudo ./configure
sudo make
sudo make install

# install TinyOS -- KMEG-blip branch
cd /home/vagrant
git clone https://github.com/SoftwareDefinedBuildings/KMEG.git -b KMEG-blip
cd KMEG/tinyos-main/tools
sudo ./Bootstrap
sudo ./configure
sudo make
sudo make install

# install platform compilers
sudo apt-get install -y gcc-msp430
SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu13"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"

  #config.vm.network :public_network, :bridge => 'eth0: Ethernet'
  #config.vm.network :forwarded_port, guest: 5000, host: 5000

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  config.vm.provision "shell", inline: $script
end
