 #
 # This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 # This class includes values of some nesC constants from
 # ./ACmeShell.h.
 #/

class ACmeShellConstants:
    NCALSEGS = 4
    ACME_DEST = 1
    ACME_CAL_REAL_PIECE = 6
    ACME_CAL_APP_PIECE = 7
    ACME_CAL_REAL = 3
    ACME_CAL_APPARENT = 4
    ACME_PERIOD = 2
    BSHELL_RESET = 52
    BSHELL_WRITE_CONFIG = 51
    BSHELL_READ = 53
    ACME_NONE = 0
    ACME_RADIO = 5
    BSHELL_READ_CONFIG = 50
    BSHELL_SET = 54
